# Setup
title:        Doppl
tagline:      Android-centric cross platform
paginate:     1

# About/contact
author:
  name:       Kevin Galligan
  url:        http://doppl.co

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown